kind: pipeline
name: default

steps:
  - name: build
    image: eignhpants/image-builder
    commands:
      - ./build/build.sh

  - name: publish-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: new_aws_key
      secret_key:
        from_secret: new_aws_secret
      repo: adventurebrave.com
      dockerfile: ecr.Dockerfile
      region: us-east-2
      registry: 208744038881.dkr.ecr.us-east-2.amazonaws.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - lambda-version
