kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: build
    image: eignhpants/image-builder
    commands:
      - ./build/build.sh

  # - name: docker push
  #   image: plugins/docker
  #   settings:
  #     repo: eignhpants/sheeta
  #     username:
  #       from_secret: dh_user_name
  #     password:
  #       from_secret: dh_pw
  #   publish:
  #     image: eignhpants/sheeta

steps:
- name: publish  
  image: plugins/ecr
  settings:
    access_key: 
      from_secret: ian_aws_key
    secret_key: 
      from_secret: ian_aws_secret
    repo: sheeta
    registry: 346096930733.dkr.ecr.us-east-1.amazonaws.com
