kind: pipeline
name: default

steps:
  - name: build
    image: eignhpants/image-builder
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret:
      AWS_SECRET_ACCESS_KEY:
        from_secret: sheeta_access_key_secret
      DISCORD_TOKEN:
        from_secret: discord_token
    commands:
      - ./build/build.sh
      - bin/main -t $DISCORD_TOKEN -b create

  - name: publish-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: sheeta_access_key_id
      secret_key:
        from_secret: sheeta_access_key_secret
      repo: adventurebrave.com
      dockerfile: ecr.Dockerfile
      region: us-east-2
      registry: 208744038881.dkr.ecr.us-east-2.amazonaws.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - lambda-version
