environment: dev
name: sheeta
region: us-east-2
kv:
  bucketName: craft-cf-bucket
  cloudRole: arn:aws:iam::346096930733:role/chat-ops-role
  # cloudRole: arn:aws:iam::346096930733:role/dev-roles-cloud-role-CloudFormationRole-13RRM8LH6E5K5
